name: Build a Pelican Website
on:
  push:
    branches: [ "dfoulks/pelican_gha" ]
  pull_request:
    branches: [ "dfoulks/pelican_gha" ]

  workflow_dispatch:
env:
  LIBCMARKDIR: /home/runner/work/infrastructure-website/infrastructure-website/cmark-gfm-0.28.3.gfm.12/lib
jobs:
  build-pelican:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ''
          ref: 'dfoulks/pelican_gha'
      - name: Install Pelican
        run: pip3 install pelican markdown ghp-import bs4
      # Optionally, if your website uses the gfm plugin uncomment the GFM blocks
      #########################
      # START BUILD GFM BLOCK #
      #########################
      - name: fetch libcmark-gfm.so buildscript
        run: wget https://raw.githubusercontent.com/apache/infrastructure-pelican/master/bin/build-cmark.sh
      - name: build libcmark-gfm.so
        run: /bin/bash ./build-cmark.sh
      #######################
      # END BUILD GFM BLOCK #
      #######################
      - name: Generate website from markdown
        run: python3 -m pelican content -o output
        working-directory: '/home/runner/work/infrastructure-website/infrastructure-website'
      ###########################
      # START GFM CLEANUP BLOCK #
      ###########################
      - name: Clean up libcmark-gfm artifacts
        run: rm -rf $(dirname $(echo $LIBCMARKDIR)) build-cmark.sh "$(dirname $(echo $LIBCMARKDIR)).orig.tar.gz"
      #########################
      # END GFM CLEANUP BLOCK #
      #########################
      - name: Open a PR against the staging branch
        uses: peter-evans/create-pull-request@v6.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: GitHub Actions Generated Pelican Build
          title: Generated Pelican Output
          body: output generated
          branch: dfoulks/gha-site
