name: Build a Pelican Website
on:
  push:
    branches: [ "SOURCE_BRANCH" ]
  workflow_dispatch:
jobs:
  build-pelican:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'SOURCE_BRANCH'
      - uses: apache/infrastructure-actions/pelican@main
        with:
          destination: 'DESTINATION_BRANCH'
          gfm: 'true'
